version: 2.1  # CircleCIのバージョン

executors:
  php-executor:  # PHP環境を定義
    docker:
      - image: circleci/php:8.2-fpm  # PHP 8.2を使用
      - image: circleci/mysql:5.7  # MySQL 5.7を使用
        environment:
          MYSQL_DATABASE: flea_market  # データベース名
          MYSQL_ROOT_PASSWORD: root  # MySQLのルートパスワード
    working_directory: ~/repo  # 作業ディレクトリ

jobs:
  test:
    executor: php-executor
    steps:
      - checkout  # コードのチェックアウト

      # 依存関係をインストール
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y zip unzip # zipツールをインストール
            composer install  # Composerで依存関係をインストール

      # 環境ファイルの設定
      - run:
          name: Configure environment
          command: |
            cp .env.example .env  # 環境ファイルをコピー
            php artisan key:generate  # アプリケーションキーを生成

      # データベースの設定
      - run:
          name: Set up database
          command: |
            php artisan migrate --force  # データベースのマイグレーションを実行

      # PHPUnitのテストを実行
      - run:
          name: Run tests
          command: |
            ./vendor/bin/phpunit --testdox  # テストを実行し、結果を出力

workflows:
  version: 2
  test:
    jobs:
      - test
