version: 2.1

executors:
  php-executor:
    docker:
      - image: circleci/php:8.2-apache  # PHP 8.2の公式Dockerイメージを使用
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: php-executor
    steps:
      - checkout  # コードをクローン
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install --no-interaction  # Composerで依存関係をインストール

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Run PHPUnit tests
          command: |
            ./vendor/bin/phpunit --configuration phpunit.xml

  deploy:
    docker:
      - image: circleci/php:8.2-apache
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production server"  # ここにデプロイ処理を追加します

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - run_tests
